### ISSUE TITLE
端末移行機能の追加

### ISSUE THREAD

**Issue by cateiru** [tdu-historylog/web#13]
現状では端末を移動した場合、local storageを移行することが不可能である。
そのため、移行可能な機能を追加したほうがいいと思う。

例:

- 合言葉による移行。
  - サーバー側に一時保存する必要がありセキュリティ的には好ましくない。
- ローカルストレージ内のデータをjson化、もしくはそれと同等なフォーマットにしてユーザー側にコピペしてもらう。
  - 情報の正しさが保証できなくなる恐れがある。
  - → 暗号化

**Comment by fujiwaraizuho** [comment]
なるほど、この機能は必要ですね。
Cloud Firestore に暗号化した情報をアップロードして合言葉で移行するのはありだと思います。
