### ISSUE TITLE
着座履歴の表示方法のアクセシビリティ向上

### ISSUE THREAD

**Issue by HIBIKI-CUBE** [tdu-historylog/web#44]
着座履歴がまだない状態で着座履歴の画面に遷移すると表が以下のように表示される。

日時 | キャンパス | 号館 | 階数 | 教室名 | 座席位置
-- | -- | -- | -- | -- | --
Null | Null | 0 | 0 | Null | Null

Nullが何かについて理解していない人も利用すると想定されるので、「まだ着座履歴がありません」などと表示した方がきっとユーザーフレンドリー。

**Comment by HIBIKI-CUBE** [comment]
![スクリーンショット2021-04-29（01 59 31）](https://user-images.githubusercontent.com/20021695/116443435-9dba8080-a88e-11eb-8629-7b4ab53b15af.png)

**Comment by cateiru** [comment]
@HIBIKI-CUBE ありがとうございます。null表示は既にローカルストレージに値が入ってて、かつ、フォーマットが違う場合に表示されます。通常、何も読んでない場合はテーブルは空になります。

しかし、空だったら空である表示があった方がいいかもしれないです。
