### ISSUE TITLE
本家リレキログからのデータ取り込み機能

### ISSUE THREAD

**Issue by HIBIKI-CUBE** [tdu-historylog/web#46]
この機能が必須というわけでもないが、一元管理するのであればリレキログ側でコピーしたデータをLogcationに貼り付けて着座履歴を取り込めるとよい。

コピーされるデータの形式は以下の通り
"",YYYY\/MM\/DD,hh:mm:ss,"jp\.ac\.dendai\/\d+-[A-Z]\d+"

**Comment by cateiru** [comment]
@HIBIKI-CUBE 凄くいい機能だと思います！
