### ISSUE TITLE
SafeArea対応

### ISSUE THREAD

**Issue by HIBIKI-CUBE** [tdu-historylog/web#51]
iOSデバイスとiPad OSデバイスで最適なユーザーエクスペリエンスを提供するにはSafeAreaに対応するとなおよい。
viewportの設定を適切に行い、env()変数を用いてpadding又はmarginで適切な余白を用意し、TrueDepthカメラ部分やホームバー部分とUIが被らないようにしつつ、画面を最大限利用する。

**Comment by cateiru** [comment]
https://dev.to/marionauta/avoid-notches-in-your-pwa-with-just-css-al7

**Comment by cateiru** [comment]
@HIBIKI-CUBE すみません、私iPhone8でSafeArea試せないので代わりに試していただけないでしょうか？

https://test-log.tdu.app

です。

**Comment by HIBIKI-CUBE** [comment]
お待たせしました。こんな感じで、ちゃんと対応出来ているようです。
![image](https://user-images.githubusercontent.com/20021695/120963900-5b456700-c79d-11eb-96fc-94eaad88e836.png)
↑通常版
![image](https://user-images.githubusercontent.com/20021695/120963904-5da7c100-c79d-11eb-8594-24a6eefb57fc.png)
↑開発版

ただ、PWAモードの時はどちらも同じ表示になっていたのでそのあたりで何か違いがあるかもしれません。
![image](https://user-images.githubusercontent.com/20021695/120963981-7dd78000-c79d-11eb-89ea-30dfce654a6f.png)
![image](https://user-images.githubusercontent.com/20021695/120963986-7fa14380-c79d-11eb-9854-2ed6ebb2bb16.png)

**Comment by cateiru** [comment]
@HIBIKI-CUBE こちら、iOS15でsafariのデザインが変わったのとPWAではなぜか適用されていないのでcloseしちゃいます。

もし、なにかあったらまたopenしてください。
