### ISSUE TITLE
ツイート機能のUX向上

### ISSUE THREAD

**Issue by fujiwaraizuho** [tdu-historylog/web#63]
現状ではツイート機能が最新の着席履歴から取得されるようになっているため、直感的ではない
座席コード読み取り時に Modal を用いて号館などの情報を明示的に表示し、ツイートを促す UI へ変更する

**Comment by cateiru** [comment]
@fujiwaraizuho Twitterやってない方からすると余計な動作が加わるので、設定に「読み取っと場合にツイートボタンを表示する」を追加したほうがいいと思います。

**Comment by fujiwaraizuho** [comment]
イメージとしては、現状 alert で出しているパース済みの情報を Modal に切り替えるのが主な変更です。
そこにボタン配置する感じですね
連続して読み取るユースケースは基本ないとおもうので大丈夫かなぁと思ってます。

**Comment by cateiru** [comment]
@fujiwaraizuho なるほど。そのほうがいいですね
