### ISSUE TITLE
QRコードが設置されていない場所に対応

### ISSUE THREAD

**Issue by HIBIKI-CUBE** [tdu-historylog/web#78]
生協前や食堂、共有スペースなど長時間滞在出来るけどQRコードが設置されていない場所について、そこにいた事を記録出来ると便利。

**Comment by HIBIKI-CUBE** [comment]
これの助けにもなるかも

> さらに、弊学は講義以外での使用も企んでおられるようなのです…
> 
> 
> 
> https://www.dendai.ac.jp/news/20201116-01.html
> 
> 
> 
> ```text
> 
> ５．今後の展開の可能性について
> 
> 「リレキログ」は今後、大学の講義以外のイベント等にも利用できるようにしたいと考えています。
> 
> ```

**Comment by HIBIKI-CUBE** [comment]
あと、教室でもEFの実験教室とかQR無いのでそれも記録したい

**Comment by cateiru** [comment]
学食や、実験室などは比較的敷地が広いため、同じ場所にいるだけでは感染リスクはそこまで高くないと考えております。そのため、このissueはクローズさせていただきたいと思います。

もし何か、問題などあれば再度issueをオープンしてください。
