### ISSUE TITLE
リレキデータが消失した

### ISSUE THREAD

**Issue by HIBIKI-CUBE** [tdu-historylog/web#82]
https://twitter.com/hibiki_cube/status/1394478579317022722

特になにかきっかけになるような出来事は身に覚えがない。ブラウザデータの削除を行なったわけでもない。
正規版も開発版も共にデータが無くなっている。
Safariでも、TwitterのWKWebViewでもデータが無い。

端末：iPhone 11 Pro Max
OS：iOS 14.6 (18F5065a) Beta
ブラウザ：Safari

**Comment by cateiru** [comment]
@HIBIKI-CUBE 詳しい経緯や、環境を教えていただけないでしょうか？

**Comment by HIBIKI-CUBE** [comment]
Safariの履歴を確認すると、今日より前のアクセスは5月10日よりも前。(そこまでしか記録がないため)

**Comment by cateiru** [comment]
@HIBIKI-CUBE 
一概にコレ！というような判定はできませんが、おそらくITP2.3によるものが原因ではないかと思われます。

[ITP まとめ「3rd フルブロックの次はCNAME対策もターゲットに😱」随時更新！](https://qiita.com/emacs_hhkb/items/d42a45eecc2d4de2f516#%E5%86%85%E5%AE%B9-5)

ログ保存をlocalStorageからindexedDBに以降する予定ですのでそれまではこまめにログをメモなどに保存していただければ幸いです。

**Comment by HIBIKI-CUBE** [comment]
なーるほどそんな制限が…

**Comment by cateiru** [comment]
@HIBIKI-CUBE ログデータ保存をlocalStorageからIndexedDBに移行します。

#83

**Comment by cateiru** [comment]
@HIBIKI-CUBE 

来週水曜日（5/26）にアップデートを実行し、完全IndexedDB保存に変更します。
すでにLocalStorageにログがある場合は、自動的にIndexedDBに移行されるためユーザーは特殊な操作を行う必要はありません。

https://test-log.tdu.app ではすでにIndexedDBに移行しているのでなにかバグがあればお知らせください。

**Comment by HIBIKI-CUBE** [comment]
ありがとうございます
